export enum OrderStatus {
  CREATED = "CREATED",
  AWAITING_APPROVAL = "AWAITING_APPROVAL",
  APPROVED = "APPROVED",
  DECLINED = "DECLINED",
  UNDER_DELIVERY = "UNDER_DELIVERY",
  FULFILLED = "FULFILLED",
  CANCELED = "CANCELED"
}
